#!/bin/bash

# 输入参数为文件名
input_file=$1

# 找到最大 ID
max_id=$(awk -F';' 'NR > 1 && $1 != "" {if ($1 > max) max=$1} END {print max}' "$input_file")

# 初始化新的 ID 计数器
new_id=$((max_id + 1))

# 处理文件
awk -F';' -v OFS='\t' -v new_id_counter="$new_id" '
NR == 1 {
    # 打印标题行，转换分隔符
    sub(/\r$/, "")  # 删除 Windows 行尾
    print
}
NR > 1 {
    # 处理 ID 列
    if ($1 == "") {
        $1 = new_id_counter++
    }
    # 替换浮点数中的逗号为点
    for (i = 1; i <= NF; i++) {
        $i = substr($i, 1)  # 确保字段不为空
        if ($i ~ /,/) {
            sub(",", ".", $i)
        }
    }
    # 打印处理后的行
    sub(/\r$/, "")  # 删除 Windows 行尾
    print
}' "$input_file" | tr -d '\r' | tr ';' '\t' | tr -cd '\11\12\15\40-\176'