#!/bin/bash

# Input parameter is the filename
input_file=$1

# Find the maximum ID
max_id=$(awk -F';' 'NR > 1 && $1 != "" {if ($1 > max) max=$1} END {print max}' "$input_file")

# Initialize new ID counter
new_id=$((max_id + 1))

# Process the file
awk -F';' -v OFS='\t' -v new_id_counter="$new_id" '
NR == 1 {
    # Print header line, convert separator
    sub(/\r$/, "")  # Remove Windows line endings
    print
}
NR > 1 {
    # Process ID column
    if ($1 == "") {
        $1 = new_id_counter++
    }
    # Replace commas with dots in floating numbers
    for (i = 1; i <= NF; i++) {
        $i = substr($i, 1)  # Ensure field is not empty
        if ($i ~ /,/) {
            sub(",", ".", $i)
        }
    }
    # Print processed line
    sub(/\r$/, "")  # Remove Windows line endings
    print
}' "$input_file" | tr -d '\r' | tr ';' '\t' | tr -cd '\11\12\15\40-\176'